# Generated by Django 4.0.3 on 2022-03-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='subject',
        ),
        migrations.AlterField(
            model_name='email',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
