# Generated by Django 4.0.3 on 2022-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_remove_email_subject_alter_email_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='body',
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
