# Generated by Django 4.0.3 on 2022-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('jwt_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_properties',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='properties.property'),
        ),
    ]
