# Generated by Django 4.0.3 on 2022-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('jwt_auth', '0003_alter_user_saved_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_properties',
            field=models.ManyToManyField(related_name='saved_by', to='properties.property'),
        ),
    ]
