# Generated by Django 4.0.3 on 2022-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_ownership_term'),
        ('jwt_auth', '0005_alter_user_saved_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_properties',
            field=models.ManyToManyField(default=[], related_name='saved_by', to='properties.property'),
        ),
    ]
