# Generated by Django 4.0.3 on 2022-03-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number_or_name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=300)),
                ('lon', models.FloatField(default=None)),
                ('lat', models.FloatField(default=None)),
                ('beds', models.IntegerField(default=None)),
                ('bathrooms', models.IntegerField(default=None)),
                ('schools', models.CharField(default=None, max_length=100)),
                ('train_stations', models.CharField(default=None, max_length=100)),
                ('level', models.IntegerField(default=None)),
                ('short_description_level1', models.CharField(default=None, max_length=300)),
                ('short_description_level2', models.CharField(default=None, max_length=300)),
                ('short_description_level3', models.CharField(default=None, max_length=300)),
                ('long_description_level1', models.TextField(default=None, max_length=3000)),
                ('long_description_level2', models.TextField(default=None, max_length=3000)),
                ('long_description_level3', models.TextField(default=None, max_length=3000)),
                ('images_level1', models.CharField(default=None, max_length=5000)),
                ('images_level2', models.CharField(default=None, max_length=5000)),
                ('images_level3', models.CharField(default=None, max_length=5000)),
                ('base_rate_level1', models.IntegerField(default=None)),
                ('base_rate_level2', models.IntegerField(default=None)),
                ('base_rate_level3', models.IntegerField(default=None)),
                ('level1_improvement_cost', models.IntegerField(default=None)),
                ('level2_improvement_cost', models.IntegerField(default=None)),
                ('for_sale', models.BooleanField(default=None)),
                ('asking_price', models.IntegerField(default=None)),
                ('currently_let', models.BooleanField(default=None)),
                ('mortgaged', models.BooleanField(default=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
