# Generated by Django 4.0.3 on 2022-03-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number_or_name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=300)),
                ('lon', models.FloatField(default=None)),
                ('lat', models.FloatField(default=None)),
                ('beds', models.IntegerField(default=None)),
                ('bathrooms', models.IntegerField(default=None)),
                ('schools', models.CharField(default=None, max_length=100)),
                ('train_stations', models.CharField(default=None, max_length=100)),
                ('level', models.IntegerField(default=None)),
                ('short_description_level1', models.CharField(default=None, max_length=300)),
                ('short_description_level2', models.CharField(default=None, max_length=300)),
                ('short_description_level3', models.CharField(default=None, max_length=300)),
                ('long_description_level1', models.TextField(default=None, max_length=3000)),
                ('long_description_level2', models.TextField(default=None, max_length=3000)),
                ('long_description_level3', models.TextField(default=None, max_length=3000)),
                ('images_level1', models.CharField(default=None, max_length=5000)),
                ('images_level2', models.CharField(default=None, max_length=5000)),
                ('images_level3', models.CharField(default=None, max_length=5000)),
                ('base_rate_level1', models.IntegerField(default=None)),
                ('base_rate_level2', models.IntegerField(default=None)),
                ('base_rate_level3', models.IntegerField(default=None)),
                ('asking_price', models.IntegerField(default=None)),
            ],
        ),
    ]
