# Generated by Django 4.0.3 on 2022-03-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ownership_term',
            field=models.IntegerField(default=None),
        ),
    ]
