# Generated by Django 4.0.3 on 2022-03-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_Value', models.IntegerField(default=None)),
                ('stamp_duty', models.IntegerField(default=None)),
                ('legal_fees', models.IntegerField(default=None)),
                ('accepted', models.BooleanField(default=None)),
                ('retracted', models.BooleanField(default=None)),
                ('time_stamp', models.DateTimeField(default=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
