# Generated by Django 4.0.3 on 2022-03-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_mortgage_offer_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_Value',
            new_name='offer_value',
        ),
    ]
