# Generated by Django 4.0.3 on 2022-03-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_offer_value_offer_offer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
