# Generated by Django 4.0.3 on 2022-03-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='legal_fees',
            new_name='fees',
        ),
    ]
