# Generated by Django 4.0.3 on 2022-03-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_rename_legal_fees_offer_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='mortgage',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='property',
        ),
    ]
