# Generated by Django 4.0.3 on 2022-03-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0002_remove_mortgage_term_expiary_mortgage_term_expiry'),
        ('properties', '0001_initial'),
        ('offers', '0006_remove_offer_mortgage_remove_offer_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='mortgage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='mortgages.mortgage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property'),
            preserve_default=False,
        ),
    ]
