# Generated by Django 4.0.3 on 2022-03-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mortgages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='expirey_date',
            new_name='term_expiary',
        ),
        migrations.AddField(
            model_name='mortgage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mortgages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
