# Generated by Django 4.0.3 on 2022-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgage',
            name='term_expiary',
        ),
        migrations.AddField(
            model_name='mortgage',
            name='term_expiry',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
