# Generated by Django 4.0.3 on 2022-03-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0002_remove_mortgage_term_expiary_mortgage_term_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='term_expiry',
            field=models.DateTimeField(default=None),
        ),
    ]
