# Generated by Django 4.0.3 on 2022-03-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='legal_fees',
            new_name='fees',
        ),
    ]
