# Generated by Django 4.0.3 on 2022-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_legal_fees_transaction_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='property_ownership_term',
            field=models.IntegerField(default=None),
        ),
    ]
